#!/bin/sh
set -e
case "${1:-}" in prereqs) exit 0;; esac
. /usr/share/initramfs-tools/hook-functions
mkdir -p "${DESTDIR}/lib/firmware"
cp -L /lib/firmware/qupv3fw.elf "${DESTDIR}/lib/firmware/qupv3fw.elf"
for mod in vfat nls_cp437 nls_iso8859-1; do manual_add_modules "$mod"; done
